framework:
    router:
        utf8: true


#app_logout:
#    path: /logout
#    methods: GET
#

#
#
#account_register:
#    path:     /register
#    defaults: { _controller: AppBundle:Account:register }
#
#account_create:
#    path:     /register/create
#    defaults: { _controller: AppBundle:Account:create }
